# Generated by Django 2.2 on 2020-07-04 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='mdedia/profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default=False, max_length=100)),
                ('project_image', models.ImageField(default=False, upload_to='media/projects')),
                ('project_description', models.TextField(default=False, max_length=300)),
                ('project_category', models.CharField(choices=[('WEB', 'WEB'), ('MOBILE', 'MOBILE'), ('DESIGN', 'DESIGN')], max_length=6)),
                ('project_url', models.URLField(default=False)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Author')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default=False, max_length=200)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('project_posted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.ProjectPost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
