# Generated by Django 2.2 on 2020-07-06 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
