# Generated by Django 2.2 on 2020-07-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_picture',
            field=models.ImageField(default=True, upload_to='mdedia/profile'),
        ),
    ]
