# Generated by Django 2.2 on 2021-05-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210518_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.ImageField(default='profile/user.png', upload_to='profile'),
        ),
    ]
